    /**
     * ============================================
     * Main JavaScript - Personal Portfolio v1.0
     * Vanilla JS SPA: i18n, filters, Unity WebGL modal, EmailJS
     * ============================================
     */

    const config = { dataFile: './portfolio.json', animationDelay: 100 };

    const appState = {
        data: null, currentFilter: 'all', isLoading: true,
        skillsSlider: { currentIndex: 0, itemsPerView: 3, totalItems: 0, isDragging: false, startX: 0, currentX: 0 }
    };

    let currentLang = localStorage.getItem('lang') || 'es';
    let translations = {};
    let profileTexts = {};

    const $ = (selector) => document.querySelector(selector);
    const $$ = (selector) => document.querySelectorAll(selector);

    function createElement(tag, attrs = {}, children = []) {
        const el = document.createElement(tag);
        Object.entries(attrs).forEach(([key, value]) => {
            if (key === 'class') { el.className = value; }
            else if (key === 'dataset') { Object.entries(value).forEach(([dk, dv]) => el.dataset[dk] = dv); }
            else if (key.startsWith('on')) {
                const ev = key.slice(2).toLowerCase();
                if (typeof value === 'string') el.setAttribute(key, value);
                else if (typeof value === 'function') el.addEventListener(ev, value);
            } else { el.setAttribute(key, value); }
        });
        children.forEach(child => {
            if (typeof child === 'string') el.appendChild(document.createTextNode(child));
            else if (child instanceof Node) el.appendChild(child);
        });
        return el;
    }

    function getCategoryIcon(category) {
        const icons = { unity: 'fa-gamepad', android: 'fa-android', software: 'fa-desktop' };
        return createElement('i', { class: `fas ${icons[category] || 'fa-folder'}` });
    }

    /**
     * ============================================
     * Internationalization (i18n) System
     * Loads language JSON and applies translations to DOM elements
     * Must be initialized before renderProjects()
     * ============================================
     */

    function getTranslation(key) {
        return key.split('.').reduce((obj, k) => obj && obj[k], translations) || key;
    }

    async function cargarIdioma(lang) {
        try {
            const response = await fetch(`lang/${lang}.json`);
            if (!response.ok) throw new Error(`Could not load lang/${lang}.json`);

            translations = await response.json();
            currentLang = lang;
            localStorage.setItem('lang', lang);
            document.documentElement.lang = lang;
            aplicarTraduccion();
            actualizarBotonesIdioma(lang);
        } catch (error) {
            console.error('Error loading language:', error);
        }
    }

    function aplicarTraduccion() {
        // 1. HTML elements with data-i18n
        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.dataset.i18n;
            const translation = getTranslation(key);
            const iconEl = el.querySelector('i');
            if (iconEl) {
                let textNode = null;
                el.childNodes.forEach(node => {
                    if (node.nodeType === Node.TEXT_NODE && node.textContent.trim()) textNode = node;
                });
                if (textNode) { textNode.textContent = ' ' + translation; }
                else { 
                    // Remove all text nodes first
                    Array.from(el.childNodes).forEach(node => {

                        if(node.nodeType === Node.TEXT_NODE) node.remove();
                    });
                    el.appendChild(document.createTextNode(' ' + translation)); 
                }
            } else {
                el.textContent = translation;
            }
        });

        // 2. Project card buttons (generated by JS)
        document.querySelectorAll('.card-link[data-link-type]').forEach(link => {
            const type = link.getAttribute('data-link-type');
            const keyMap = { code: 'projects.code', view: 'projects.view', download: 'projects.download' };
            if (keyMap[type]) {
                let textNode = null;
                link.childNodes.forEach(node => {
                    if (node.nodeType === Node.TEXT_NODE && node.textContent.trim()) textNode = node;
                });
                if (textNode) {
                    textNode.textContent = ' ' + getTranslation(keyMap[type]);
                } else {
                    Array.from(link.childNodes).forEach(node => {
                        if (node.nodeType === Node.TEXT_NODE) node.remove();
                    });

                    link.appendChild(document.createTextNode('' + getTranslation(keyMap[type])));
                }
            }
        });

        // 3. Form Placeholders
        const nameInput = document.getElementById('name');
        const emailInput = document.getElementById('email');
        const messageInput = document.getElementById('message');
        if (nameInput) nameInput.placeholder = getTranslation('contact.name');
        if (emailInput) emailInput.placeholder = getTranslation('contact.email');
        if (messageInput) messageInput.placeholder = getTranslation('contact.message');

        // 4. Dynamic profile texts
        if (profileTexts.tagline_es) {
            const taglineEl = $('#profileTagline');
            const bioEl = $('#profileBio');
            const bioFullEl = $('#profileFullBio');
            if (taglineEl) taglineEl.textContent = profileTexts[`tagline_${currentLang}`] || profileTexts.tagline_es;
            if (bioEl) bioEl.textContent = profileTexts[`bio_${currentLang}`] || profileTexts.bio_es;
            if (bioFullEl) bioFullEl.textContent = profileTexts[`fullBio_${currentLang}`] || profileTexts.fullBio_es;
        }

        // 5. Translate project descriptions
        if (appState.data && appState.data.projects) {
            appState.data.projects.forEach(project => {
                const el = document.querySelector(`[data-project-id="${project.id}"]`);
                if (el) {
                    const desc = currentLang === 'en'
                        ? (project.shortDescription_en || project.shortDescription)
                        : project.shortDescription;
                    el.textContent = desc;
                }
            });
        }
    }

    function actualizarBotonesIdioma(lang) {
        document.querySelectorAll('.language-switch button').forEach(btn => {
            btn.classList.toggle('active', btn.textContent.toLowerCase() === lang.toLowerCase());
        });
    }

    function guardarTextosPerfilBilingue(data) {
        const p = data.profile;
        profileTexts.tagline_es = p.tagline || '';
        profileTexts.tagline_en = p.tagline_en || p.tagline || '';
        profileTexts.bio_es = p.bio || '';
        profileTexts.bio_en = p.bio_en || p.bio || '';
        profileTexts.fullBio_es = p.fullBio || p.bio || '';
        profileTexts.fullBio_en = p.fullBio_en || p.bio_en || '';
    }

    /**
     * ============================================
     * Data Loading
     * Fetches portfolio.json and initializes app state
     * ============================================
     */

    async function loadPortfolioData() {
        try {
            const response = await fetch(config.dataFile);
            if (!response.ok) throw new Error('Error loading portfolio.json');
            appState.data = await response.json();
            appState.isLoading = false;
            return appState.data;
        } catch (error) {
            console.error('Error loading data:', error);
            showError('Error loading portfolio');
            return { profile: {}, projects: [], skills: [] };
        }
    }

    // ============================================
    // Profile Render
    // ============================================

    function renderProfile(data) {
        const { profile } = data;
        $('#profileName').textContent = profile.name || '';
        $('#profileTagline').textContent = profile.tagline || '';
        $('#profileBio').textContent = profile.bio || '';
        
        const fullBioEl = $('#profileFullBio');
        if (fullBioEl) fullBioEl.textContent = profile.fullBio || profile.bio || '';

        const avatarImg = $('#profileAvatar');
        if (avatarImg && profile.avatar) { avatarImg.src = profile.avatar; avatarImg.alt = profile.name; }

        $('#footerName').textContent = profile.name;
        $('#currentYear').textContent = new Date().getFullYear();

        const socialContainer = $('#socialLinks');
        if (profile.social && socialContainer) {
            const socials = [
                { key: 'github',   icon: 'fab fa-github',  title: 'GitHub' },
                { key: 'gitlab',   icon: 'fab fa-gitlab',  title: 'GitLab' },
                { key: 'linkedin', icon: 'fab fa-linkedin', title: 'LinkedIn' },
                { key: 'twitter',  icon: 'fab fa-twitter',  title: 'Twitter' },
                { key: 'itchio',   icon: 'fab fa-itch-io',  title: 'Itch.io' }
            ];
            socials.forEach(({ key, icon, title }) => {
                if (profile.social[key]) {
                    const link = createElement('a', { href: profile.social[key], target: '_blank', rel: 'noopener noreferrer', title, class: 'social-link' });
                    link.appendChild(createElement('i', { class: icon }));
                    socialContainer.appendChild(link);
                }
            });
        }

        $('#contactEmail').textContent = profile.email;
        $('#contactLocation').textContent = profile.location || 'Disponible remotamente';
    }

    // ============================================
    // Render Projects
    // ============================================

    function renderProjects(projects) {
        const container = $('#projectsGrid');
        if (!projects || projects.length === 0) {
        container.innerHTML = '<p class="loading">No projects available</p>';
            return;
        }
        $('#projectCount').textContent = projects.length;

        const projectCards = projects.map(project => {
            const card = createElement('div', { class: 'project-card', dataset: { category: project.category } });

            if (project.thumbnail) {
                card.appendChild(createElement('img', {
                    src: project.thumbnail, alt: project.name, class: 'card-image', loading: 'lazy',
                    onerror: "this.style.display='none'; this.nextElementSibling.style.display='flex'"
                }));
            }

            card.appendChild(createElement('div', {
                class: 'card-image-placeholder',
                style: 'display: ' + (project.thumbnail ? 'none' : 'flex')
            }, [getCategoryIcon(project.category)]));

            if (project.category === 'unity' && project.links?.play) {
                const pb = createElement('button', { class: 'play-btn', title: 'Jugar' });
                pb.onclick = () => openGameModal(project.links.play);
                pb.appendChild(createElement('i', { class: 'fas fa-play' }));
                card.appendChild(pb);
            }

            const tagsContainer = createElement('div', { class: 'card-tags' });
            (project.technologies || []).forEach(tech => {
                tagsContainer.appendChild(createElement('span', { class: `tag tag-${project.category}` }, [tech]));
            });

            const linksContainer = createElement('div', { class: 'card-links' });

            // data-link-type allows getTranslation() to re-translate on language change
            if (project.links?.github) {

                const a = createElement('a', { href: project.links.github, target: '_blank', rel: 'noopener noreferrer', class: 'card-link', 'data-link-type': 'code' });
                a.appendChild(createElement('i', { class: 'fab fa-github' }));
                a.appendChild(document.createTextNode(' ' + getTranslation('projects.code')));
                linksContainer.appendChild(a);
            }
            if (project.links?.play) {
                const a = createElement('a', { href: project.links.play, target: '_blank', class: 'card-link', 'data-link-type': 'view' });
                a.appendChild(createElement('i', { class: 'fas fa-external-link-alt' }));
                a.appendChild(document.createTextNode(' ' + getTranslation('projects.view')));
                linksContainer.appendChild(a);
            }
            if (project.links?.download) {
                const a = createElement('a', { href: project.links.download, download: '', class: 'card-link', 'data-link-type': 'download' });
                a.appendChild(createElement('i', { class: 'fas fa-download' }));
                a.appendChild(document.createTextNode(' ' + getTranslation('projects.download')));
                linksContainer.appendChild(a);
            }

            card.appendChild(createElement('div', { class: 'card-content' }, [
                createElement('h3', { class: 'card-title' }, [project.name]),
                createElement('p', { class: 'card-description', 'data-project-id': project.id }, [project.shortDescription || project.description]),
                tagsContainer,
                linksContainer
            ]));

            return card;
        });

        container.append(...projectCards);
    }

    // ============================================
    // Render Skills
    // ============================================

    function renderSkills(skills) {
        const container = $('#skillsGrid');
        if (!skills || skills.length === 0) { container.innerHTML = '<p class="loading">There are no skills.</p>'; return; }

        container.append(...skills.map(skill => {
            const item = createElement('div', { class: 'skill-item' });
            const iconEl = skill.icon
                ? createElement('img', { src: skill.icon, alt: skill.name, class: 'skill-icon-img', style: 'width:30px;height:30px;' })
                : document.createTextNode(skill.name.charAt(0));
            item.append(
                createElement('div', { class: 'skill-icon' }, [iconEl]),
                createElement('div', { class: 'skill-info' }, [
                    createElement('h4', { class: 'skill-name' }, [skill.name]),
                    createElement('div', { class: 'skill-level' }, [
                        createElement('div', { class: 'skill-progress', style: `width: ${skill.level || 0}%` })
                    ])
                ])
            );
            return item;
        }));
    }

    // ============================================
    // Contact Render
    // ============================================

    function renderContact(data) {
        const { contact } = data;
        if (contact?.fields) {
            const n = $('#name'), e = $('#email'), m = $('#message');
            if (n && contact.fields.name) n.placeholder = contact.fields.name;
            if (e && contact.fields.email) e.placeholder = contact.fields.email;
            if (m && contact.fields.message) m.placeholder = contact.fields.message;
        }
        if (data.cv?.file) {
            const cvBtn = $('#cvDownloadBtn');
            const downloadCV = $('#downloadCV');
            if (cvBtn) { cvBtn.href = data.cv.file; if (data.cv.downloadName) cvBtn.download = data.cv.downloadName; }
            if (downloadCV) { downloadCV.href = data.cv.file; if (data.cv.downloadName) downloadCV.download = data.cv.downloadName; }
        }
    }

    // ============================================
    // Slider
    // ============================================

    function initSkillsSlider(skills) {
        const sc = document.getElementById('skillsScroll');
        if (!sc) return;

        const prev = document.getElementById('skillsPrev');
        const next = document.getElementById('skillsNext');
        const countEl = document.getElementById('skillsCount');
        if (countEl) countEl.innerHTML = `${skills.length} <span data-i18n="skills.count"></span>`;

        const amt = 250;
        if (prev) prev.addEventListener('click', () => sc.scrollBy({ left: -amt, behavior: 'smooth' }));
        if (next) next.addEventListener('click', () => sc.scrollBy({ left: amt, behavior: 'smooth' }));

        const upd = () => {
            if (prev) prev.disabled = sc.scrollLeft <= 0;
            if (next) next.disabled = sc.scrollLeft >= sc.scrollWidth - sc.clientWidth - 1;
        };
        sc.addEventListener('scroll', upd);
        upd();

        let tx = 0;
        sc.addEventListener('touchstart', e => { tx = e.changedTouches[0].screenX; }, { passive: true });
        sc.addEventListener('touchend', e => {
            const d = tx - e.changedTouches[0].screenX;
            if (Math.abs(d) > 50) sc.scrollBy({ left: d > 0 ? amt : -amt, behavior: 'smooth' });
        }, { passive: true });
    }

    // ============================================
    // Filters and Modal
    // ============================================

    function filterProjects(category) {
        appState.currentFilter = category;
        $$('.filter-btn').forEach(btn => btn.classList.toggle('active', btn.dataset.filter === category));
        $$('.project-card').forEach(card => card.classList.toggle('hidden', category !== 'all' && card.dataset.category !== category));
    }

    function openGameModal(gameUrl) {
        if (!gameUrl) return;
        $('#gameFrame').src = gameUrl;
        $('#gameModal').classList.add('active');
        document.body.style.overflow = 'hidden';
    }

    function closeGameModal() {
        $('#gameFrame').src = '';
        $('#gameModal').classList.remove('active');
        document.body.style.overflow = '';
    }

    // ============================================
    // Navigation
    // ============================================

    function setupNavigation() {
        $$('a[href^="#"]').forEach(anchor => {
            anchor.addEventListener('click', function (e) {
                e.preventDefault();
                const target = $(this.getAttribute('href'));
                if (target) target.scrollIntoView({ behavior: 'smooth' });
            });
        });

        const sections = $$('section[id]');
        const navLinks = $$('.nav-link');
        let scrollTimeout;

        window.addEventListener('scroll', () => {
            if (scrollTimeout) return;
            scrollTimeout = setTimeout(() => {
                scrollTimeout = null;
                let current = '';
                sections.forEach(s => { if (scrollY >= s.offsetTop - 200) current = s.getAttribute('id'); });
                navLinks.forEach(link => {
                    link.classList.remove('active');
                    if (link.getAttribute('href') === `#${current}`) link.classList.add('active');
                });
            }, 100);
        });

        const navToggle = $('#navToggle');
        const navMenu = $('#navMenu');
        if (navToggle && navMenu) {
            navToggle.addEventListener('click', () => navMenu.classList.toggle('active'));
            navLinks.forEach(link => link.addEventListener('click', () => navMenu.classList.remove('active')));
        }
    }

    // ============================================
    // EmailJS Form — DO NOT MODIFY
    // ============================================

    function setupContactForm() {
        const submitBtn = document.getElementById('submit-btn');
        const form = document.getElementById('contact-form');
        if (!submitBtn || !form) return;

        // CONFIGURACION EMAILJS - NO TOCAR
        const emailjsConfig = { publicKey: '9bdYHELMIBud0OpOW', serviceId: 'service_gj0z1c7', templateId: 'template_likc0ei' };
        if (typeof emailjs !== 'undefined') emailjs.init(emailjsConfig.publicKey);

        form.addEventListener('submit', async (e) => {
            e.preventDefault();
            if (!form.checkValidity()) { form.reportValidity(); return; }

            const originalText = submitBtn.innerHTML;
            submitBtn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Enviando...';
            submitBtn.disabled = true;

            try {
                const templateParams = {
                    name: document.getElementById('name').value,
                    email: document.getElementById('email').value,
                    message: document.getElementById('message').value
                };
                if (typeof emailjs !== 'undefined') {
                    await emailjs.send(emailjsConfig.serviceId, emailjsConfig.templateId, templateParams);
                    showNotification('Mensaje enviado correctamente! Te respondere pronto.', 'success');
                }
                form.reset();
            } catch (error) {
                showNotification('Error al enviar: ' + error.message, 'error');
            } finally {
                submitBtn.innerHTML = originalText;
                submitBtn.disabled = false;
            }
        });
    }

    function showNotification(message, type = 'info') {
        const n = createElement('div', {
            class: `alert alert-${type === 'success' ? 'success' : 'error'}`,
            style: `position:fixed;top:20px;right:20px;z-index:9999;background:${type === 'success' ? '#28a745' : '#dc3545'};color:white;padding:15px 20px;border-radius:5px;`
        }, [message]);
        document.body.appendChild(n);
        setTimeout(() => n.remove(), 5000);
    }

    function showError(message) { showNotification(message, 'error'); }

    // ============================================
    // Inicialización
    // ============================================

    async function init() {
        console.log('Inicializando portafolio...');
        document.body.classList.add('content-loading');

        const data = await loadPortfolioData();

        if (data) {
            renderProfile(data);
            guardarTextosPerfilBilingue(data);
            renderProjects(data.projects);
            renderSkills(data.skills);
            renderContact(data);

            if (data.skills?.length > 0) initSkillsSlider(data.skills);

            setupNavigation();
            setupContactForm();

            $$('.filter-btn').forEach(btn => btn.addEventListener('click', () => filterProjects(btn.dataset.filter)));

            const modalClose = $('#modalClose');
            if (modalClose) modalClose.addEventListener('click', closeGameModal);
            const gameModal = $('#gameModal');
            if (gameModal) gameModal.addEventListener('click', e => { if (e.target.id === 'gameModal') closeGameModal(); });
            document.addEventListener('keydown', e => { if (e.key === 'Escape') closeGameModal(); });

            document.body.classList.remove('content-loading');
            const loader = document.getElementById('loader-overlay');
            if (loader) loader.classList.add('hidden');

            console.log('Portafolio cargado correctamente');
        }
    }

    document.addEventListener('DOMContentLoaded', async () => {
        const lang = localStorage.getItem('lang') || 'es';
        await init();
        await cargarIdioma(lang);
    });